# NUMPY ASSIGNMENT

## Theoretical Questions:

In [1]:
#1. Explain the purpose and advantages of Numpy in scientific computing and data analysis.How does it enhance
#   python's capabilities for numerical operations?
#Ans.NumPy enhances Python's capabilities for numerical operations by providing a high-performance multidimensional array object and a        suite of tools for manipulating these arrays. This library is fundamental for scientific computing and data analysis, offering           speed, simplicity, and interoperability. 
#Purpose of NumPy:
#Efficient Numerical Operations:
#   NumPy provides a fast and efficient way to perform numerical computations, especially on large datasets. It uses compiled C code for     array operations, making them significantly faster than using Python lists for the same tasks. 
#Multidimensional Arrays (ndarrays):
#   NumPy's core data structure is the ndarray, which is a homogeneous, N-dimensional array that can store data of the same type. 
#   Vectorized Operations:
#   NumPy's array operations are vectorized, meaning they operate on entire arrays at once rather than individual elements, reducing the     need for explicit looping and making code more concise. 
#Advantages of NumPy:
#Efficiency:
#   NumPy's C-based implementation and vectorized operations lead to significant speed gains when performing numerical computations. 
#Memory Efficiency:
#   NumPy arrays store data in contiguous memory blocks, reducing memory overhead compared to Python lists. 
#Interoperability:
#   NumPy seamlessly integrates with other Python libraries like Pandas, SciPy, and Matplotlib, facilitating a cohesive data science         workflow. 
#Simplicity:
#   NumPy's intuitive syntax and vectorized operations simplify complex numerical computations, reducing the need for explicit looping. 
#   Wide Range of Functions:
#   NumPy provides a comprehensive set of functions for performing various mathematical, statistical, and linear algebra operations on       arrays. 
#How NumPy Enhances Python's Capabilities:
#Speed:
#   NumPy's array operations are much faster than traditional Python list operations, making it suitable for computationally intensive       tasks. 
#Data Analysis:
#   NumPy is a cornerstone of data analysis, providing tools for data cleaning, transformation, and aggregation. 
#   Scientific Computing:
#   NumPy is essential for scientific computing, enabling tasks like linear algebra, statistical analysis, and signal processing. 
#Machine Learning:
#   NumPy is widely used by machine learning libraries like TensorFlow and scikit-learn for mathematical computations. 

In [2]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy.when would you use one over the other?
#Ans.In NumPy, both np.mean() and np.average() calculate averages, but np.average() offers more flexibility, including the ability to 
#    compute weighted averages, while np.mean() always calculates an unweighted arithmetic mean. np.average() can be used for weighted
#    averages by providing a weights parameter, while np.mean() does not have this feature. 

In [3]:
#3. Describe the methods for reversing a NumPy array along different axes.Provide examples for 1D and 2D arrays.
#Ans.NumPy provides several methods to reverse arrays along specified axes:
#Slicing:
#   It creates a reversed view of the array without modifying the original. For a 1D array, arr[::-1] reverses the order of elements. In
#   2D arrays, arr[::-1, :] reverses rows, and arr[:, ::-1] reverses columns.
#numpy.flip():
#   This function reverses the elements along a given axis. It takes the array and the axis as input. If no axis is specified, it     
#   reverses the order of all elements, flattening the array if necessary.
#numpy.flipud():
#   Specifically for 2D arrays, it flips the array vertically (up-down), equivalent to numpy.flip(arr, axis=0).
#numpy.fliplr():
#   Also for 2D arrays, it flips the array horizontally (left-right), equivalent to numpy.flip(arr, axis=1).

In [6]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("Original 1D array:", arr_1d)

# Reverse using slicing
reversed_1d_slice = arr_1d[::-1]
print("Reversed 1D array (slice):", reversed_1d_slice)

# Reverse using numpy.flip()
reversed_1d_flip = np.flip(arr_1d)
print("Reversed 1D array (flip):", reversed_1d_flip)

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original 2D array:\n", arr_2d)

# Reverse rows using slicing
reversed_2d_rows_slice = arr_2d[::-1, :]
print("Reversed 2D array (rows, slice):\n", reversed_2d_rows_slice)

# Reverse columns using slicing
reversed_2d_cols_slice = arr_2d[:, ::-1]
print("Reversed 2D array (columns, slice):\n", reversed_2d_cols_slice)

# Reverse using numpy.flip() along axis 0 (rows)
reversed_2d_rows_flip = np.flip(arr_2d, axis=0)
print("Reversed 2D array (rows, flip):\n", reversed_2d_rows_flip)

# Reverse using numpy.flip() along axis 1 (columns)
reversed_2d_cols_flip = np.flip(arr_2d, axis=1)
print("Reversed 2D array (columns, flip):\n", reversed_2d_cols_flip)

# Reverse using numpy.flipud()
reversed_2d_flipud = np.flipud(arr_2d)
print("Reversed 2D array (flipud):\n", reversed_2d_flipud)

# Reverse using numpy.fliplr()
reversed_2d_fliplr = np.fliplr(arr_2d)
print("Reversed 2D array (fliplr):\n", reversed_2d_fliplr)

Original 1D array: [1 2 3 4 5]
Reversed 1D array (slice): [5 4 3 2 1]
Reversed 1D array (flip): [5 4 3 2 1]
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D array (rows, slice):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed 2D array (columns, slice):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Reversed 2D array (rows, flip):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed 2D array (columns, flip):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Reversed 2D array (flipud):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed 2D array (fliplr):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [10]:
#4.How can you determine  the data type of elements in a NumPy array? Discuss the importance of datatypes in a memory management and 
#  performance.
#Ans.To determine the data type of elements in a NumPy array, you can use the dtype attribute of the array. This attribute reveals the  
     #data type of the array's elements. Data types are crucial for memory management and performance because they directly influence how 
     #much memory each element occupies and how efficiently operations can be performed on the array. 
#Determining Data Type:
#dtype Attribute: The most straightforward way to get the data type is by accessing the dtype attribute of the NumPy array. 
#example.
arr = np.array((1, 2, 3))
print(arr.dtype) # Output: int64 (or int32, depending on the system)
#Data Type Objects: NumPy provides data type objects (dtypes) that store information about the data type, including its name, character 
#code, and more.
#example:
arr = np.array([1.0, 2.0, 3.0])
print(arr.dtype.name)  # Output: float64
print(arr.dtype.char) # Output: f
print(arr.dtype.kind) # Output: f (floating-point)
#Importance of Data Types:
#Memory Management:
#Choosing the right data type can significantly impact memory usage. Smaller data types (e.g., int8, float32) require less memory per 
#element than larger ones (e.g., int64, float64). This is particularly important for large datasets.
#Performance:
#Certain operations can be faster with specific data types. For example, some hardware instructions are optimized for particular data 
#types, and using an appropriate type can lead to faster computations.

import sys

# Integer array (int32)
arr_int = np.array([1, 2, 3], dtype=np.int32)
print(f"Integer array data type: {arr_int.dtype}")
print(f"Integer array item size: {arr_int.itemsize} bytes")
print(f"Integer array memory size: {sys.getsizeof(arr_int)} bytes")

# Floating-point array (float64)
arr_float = np.array([1.0, 2.0, 3.0])
print(f"Float array data type: {arr_float.dtype}")
print(f"Float array item size: {arr_float.itemsize} bytes")
print(f"Float array memory size: {sys.getsizeof(arr_float)} bytes")
#In this example, you can see how the int32 array uses 4 bytes per element (or 12 bytes total) while the default float64 array uses 8 
#bytes per element (or 24 bytes total). This demonstrates the difference in memory usage based on the data type. 

int32
float64
d
f
Integer array data type: int32
Integer array item size: 4 bytes
Integer array memory size: 124 bytes
Float array data type: float64
Float array item size: 8 bytes
Float array memory size: 136 bytes


In [ ]:
#5.Define ndarrays in NumPy and explain their key features. How do they differ from standard python lists?
#Ans.In NumPy, an ndarray (N-dimensional array) is a powerful data structure used for storing and manipulating large, homogeneous      
#collections of data. It's a multi-dimensional container of items of the same type and size. Compared to Python lists, ndarrays offer   
#significant advantages in speed and efficiency for numerical computations, making them essential for scientific computing and data analysis. 

#Key Features of NumPy ndarrays:
#Homogeneous:
#   All elements within an ndarray must be of the same data type (dtype). 
#Multidimensional:
#   ndarrays can have multiple dimensions, allowing for the representation of complex data structures like matrices and tensors. 
#Fixed Size:
#   The size of an ndarray is typically fixed at creation, although it can be adjusted with some operations that might create new arrays and delete 
#   the original. 
#Efficient Storage:
#   ndarrays store data in contiguous memory blocks, which improves performance for vectorized operations. 
#Data Type Object (dtype):
#   Each ndarray has an associated dtype that specifies the type of elements it stores. 
#Vectorized Operations:
#   NumPy enables efficient element-wise operations on entire arrays without explicit loops. 
#Array Slicing and Indexing:
#   ndarrays can be accessed and modified using various indexing and slicing techniques. 

#Differences from Python Lists:
#Homogeneity:
#   Python lists can contain elements of different data types, while ndarrays must be homogeneous. 
#Size:
#   Python lists are dynamic and can grow or shrink as needed. NumPy arrays typically have a fixed size at creation. 
#Performance:
#   ndarrays are optimized for numerical computations and offer significantly faster performance than Python lists for vectorized 
#   operations. 
#Memory Usage:
#   NumPy arrays can be more memory-efficient than Python lists, especially for large datasets. 
#Methods and Functions:
#   NumPy provides a rich set of built-in functions and methods for working with arrays, such as linear algebra operations, Fourier 
#   transforms, and random number generation. Python lists have more general-purpose methods for list manipulation. 

In [4]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
#Ans.NumPy arrays significantly outperform Python lists for numerical operations, especially with large datasets, due to their optimized storage,
#    vectorized operations, and efficient memory usage. NumPy arrays store elements of the same data type in contiguous memory,      while Python lists
#    can hold objects of different types, leading to increased overhead. NumPy's vectorized operations, which perform      operations on entire arrays
#    at once, avoid explicit looping, resulting in substantial speed gains. 

In [7]:
#7. Compare vstack() and hstack() functions in NumPy.Provide examples demonstrating their usage and output.
#Ans.In NumPy, vstack() stacks arrays vertically along the rows, while hstack() stacks them horizontally along the columns. Both          
    #functions are used to combine arrays, but they do so in different directions. 
    #vstack() (Vertical Stack)
    #Combines arrays vertically, creating a new array where the arrays are stacked on top of each other. 
    #The arrays being stacked must have the same number of columns. 
    #Effectively concatenates along the first axis (axis=0). 

#Example:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

stacked_vertical = np.vstack((arr1, arr2))
print(stacked_vertical)

#hstack() (Horizontal Stack)
#Combines arrays horizontally, placing them side by side.
#The arrays being stacked must have the same number of rows.
#Effectively concatenates along the second axis (axis=1).

#Example:

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

stacked_horizontal = np.hstack((arr1, arr2))
print(stacked_horizontal)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [8]:
#8.Explain the differences between fliplr() and flipud() methods in NumPy,including their effects on various array dimensions.
#Ans.In NumPy, fliplr() flips a 2D array horizontally (left to right), while flipud() flips a 2D array vertically (up to down). Both fliplr() and
#    flipud() are specialized versions of the more general np.flip() function, which can flip along any axis. For fliplr(),this corresponds to flipping
#    along the second axis (axis=1), and for flipud(), it corresponds to flipping along the first axis(axis=0). 
#Effects on Various Array Dimensions:
#1D Arrays:
#    fliplr() raises a ValueError because it's designed for 2D arrays and only works with the second axis. 
#    flipud() works the same way as np.flip(a, axis=0) and reverses the order of elements in the 1D array. 
#2D Arrays:
#    fliplr() flips the array horizontally, reversing the order of elements within each row. 
#    flipud() flips the array vertically, reversing the order of elements within each column. 
#3D+ Arrays:
#    fliplr() flips the array along the second axis (the "columns" axis). 
#    flipud() flips the array along the first axis (the "rows" axis). 
#    For example, in a 3D array a.shape = (4, 17, 17), fliplr(a) would flip each of the 4 "planes" (the 17x17 matrices within the 3D array) horizontally,
#    while flipud(a) would flip the entire 3D array vertically. 
#In essence:
#    fliplr() is equivalent to np.flip(a, axis=1) for 2D arrays and flips horizontally along the second axis for multi-dimensional arrays.
#    flipud() is equivalent to np.flip(a, axis=0) for 2D arrays and flips vertically along the first axis for multi-dimensional arrays. 

In [12]:
#9.Discuss the functionality of the array_split() method in NumPy.How does it handle uneven splits?
#Ans.The NumPy function array_split() divides an array into multiple sub-arrays, even if the division doesn't result in equal-sized 
    #chunks. It handles uneven splits by distributing the "remainder" elements across the first few sub-arrays, ensuring that all 
    #elements of the original array are included in the split. 
#How it works:
#1. Input:
 #The function takes a NumPy array and an integer indices_or_sections as input. This integer specifies how many sections or splits to 
 #create. 
#2. Uneven Split:
 #If the length of the array is not divisible by the number of desired sections, the resulting sub-arrays will have different sizes. 
 #Some sub-arrays will be larger than others. 
#3. Distribution of Remainder:
 #array_split() distributes the "remainder" elements (elements not divisible evenly) across the first few sub-arrays, making them 
 #slightly larger than the others. 

#Example
# Original array
x = np.arange(8.0)

# Splitting into 3 sections
splits = np.array_split(x, 3)

# Output: [array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]
print(splits)
#In this example, the 8 elements of x are split into 3 sub-arrays. The first two sub-arrays have 3 elements each, while the third 
#sub-array has only 2 elements. The uneven split is managed by ensuring that all elements are included in the sub-arrays. 

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]


In [9]:
#10.Explain the concepts of vectorisation and broadcasting in NumPy.How do they contribute to efficient array operations?
#Ans.In NumPy, vectorization involves performing operations on entire arrays at once, instead of iterating through individual elements. Broadcasting is
#   a mechanism that enables NumPy to handle operations on arrays with different shapes by conceptually "stretching" the smaller array to match the
#   larger one. Both significantly enhance efficiency in array operations. 
#Vectorization:
#Definition:
#Vectorization replaces loops with vectorized operations, enabling NumPy to perform operations on all elements of an array simultaneously. 
#Benefits:
#Speed: Vectorized operations are significantly faster than explicit Python loops due to C implementation and efficient memory usage. 
#Conciseness: Code becomes more readable and compact. 
#Memory Efficiency: NumPy arrays are designed for efficient storage and manipulation, further enhancing performance. 

#Broadcasting:
#Definition:
#Broadcasting allows NumPy to perform operations on arrays with different shapes by implicitly expanding the smaller array to match the larger one. 
#Benefits:
#Efficiency: Broadcasting avoids explicit reshaping or looping, leading to faster execution. 
#Flexibility: It enables operations on arrays with varying shapes without the need for manual reshaping. 
#Code Readability: It simplifies operations, making code more concise and understandable. 

# Practical Questions

In [22]:
#1.Create a 3x3 NumPy array with random integers between 1 and 100.Then,interchange itd rows and columns.
#Ans.
random_array = np.random.randint(1,101, size=(3, 3))
transposed_array = random_array.T
print("Original array:\n",random_array)
print("\nTransposed array:\n",transposed_array)

Original array:
 [[44 27  2]
 [30 27 91]
 [15 90 83]]

Transposed array:
 [[44 30 15]
 [27 27 90]
 [ 2 91 83]]


In [23]:
#2.Generate a 1D NumPy array with 10 elements.Reshape it into a 2x5 array,then into a 5x2 array.
#Ans.
arr_1d = np.arange(10)
print("1D Array:")
print(arr_1d)

arr_2x5 = arr_1d.reshape(2, 5)
print("\n2x5 Array:")
print(arr_2x5)

arr_5x2 = arr_2x5.reshape(5,2)
print("\n5x2 Array:")
print(arr_5x2)

1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [24]:
#3.Create a 4x4 NumPy array with random float values.Add a border of zeroes around it,resulting in a 6x6 array.
#Ans.
random_array = np.random.rand(4, 4)
bordered_array = np.zeros((6, 6))
bordered_array[1:5,1:5] = random_array
print(bordered_array)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.70019038 0.03519422 0.50229108 0.39670831 0.        ]
 [0.         0.09375583 0.83813604 0.86993053 0.72610768 0.        ]
 [0.         0.09898591 0.17241086 0.14390155 0.6877647  0.        ]
 [0.         0.42776432 0.54972532 0.8290364  0.11354253 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [25]:
#4.Using NumPy,create an array of integers from 10 to 60 with a step of 5.
#Ans.
arr = np.arange(10, 61, 5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


In [17]:
#5.Create a NumPy array of strings['python','numpy','pandas'].Apply different case transformations (uppercase,lowercase,title case,etc.)
  #to each element.
#Ans.
x = np.array(['python','numpy','pandas'])
print("Original_array:",x)
#Converting all characters to Uppercase
uppered_case =np.char.upper(x)
#Converting all characters to Lowercase
lowered_case = np.char.lower(x)
#Converting all characters to Titlecase
title_case = np.char.title(x)
#Displaying the modifying arrays
print("Uppercase:",uppered_case)
print("Lowercase:",lowered_case)
print("Titlecase:",title_case)

Original_array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Titlecase: ['Python' 'Numpy' 'Pandas']


In [26]:
#6.Generate a NumPy array of words.insert a space between each character of every word in the array.
#Ans.
word_list = ['apple','banana','cherry']
word_array = np.array(word_list)
spaced_array = np.array([' '.join(word) for word in word_array])
print(spaced_array)

['a p p l e' 'b a n a n a' 'c h e r r y']


In [14]:
#7.Create two 2D NumPy arrays and perform element-wise addition,subtraction,multiplication,and division.
#Ans.
#create a 2D array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[4, 5], [7, 8]])
#addition
addition = arr1 + arr2
print("Addition:", addition)
#subraction
subtraction = arr1 - arr2
print("Subtraction:",subtraction)
#multiplication
multiplication = arr1 * arr2
print("Multiplication:",multiplication)
#Division
division =  arr1 / arr2
print("Division:",division)

Addition: [[ 5  7]
 [10 12]]
Subtraction: [[-3 -3]
 [-4 -4]]
Multiplication: [[ 4 10]
 [21 32]]
Division: [[0.25       0.4       ]
 [0.42857143 0.5       ]]


In [13]:
#8.Use NumPy to create a 5x5 identity matrix,then extract its diagonal elements.
#Ans.
#Create a 5x5 identity matrix
identity_matrix = np.eye(5, 5)
#extract the diagonal elements using np.diag()
diagonal_elements = np.diag(identity_matrix)
print('identity matrix')
print(identity_matrix)
print('Extracting diagonal elements')
print(diagonal_elements)

identity matrix
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Extracting diagonal elements
[1. 1. 1. 1. 1.]


In [35]:
#9.Generate a NumPy array of 100 random integers between 0 and 1000.find and display all prime numbersin this array.
#Ans.
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % (i + 2) == 0:
            return False
        i += 6
    return True

random_array = np.random.randint(0, 1001, 100)
prime_numbers = [num for num in random_array if is_prime(num)]
print("Prime numbers in the array:",prime_numbers)      

Prime numbers in the array: [769, 827, 701, 319, 97, 223, 971, 11, 635, 515, 193, 577, 193, 887, 781, 869, 905, 235, 101, 205, 139, 953, 421, 167, 745, 79, 955]


In [8]:
#10.Create a NumPy array representing daily temperatures for a month.Calculate and display the weekly averages.
#Ans.
np.random.seed(42)
daily_temps = np.random.uniform(15, 28, 28)
weekly_temps = daily_temps.reshape(4, 7)
weekly_avg_temps = np.mean(weekly_temps, axis = 1)

for i, avg_temps in enumerate(weekly_avg_temps):
    print(f"Week {i + 1}: {avg_temps:2f} degree Celsius")

Week 1: 20.619721 degree Celsius
Week 2: 22.819760 degree Celsius
Week 3: 19.697188 degree Celsius
Week 4: 20.113001 degree Celsius
